export const API_V1_RESOURCES = [
  { name: "root", path: "/api/v1", methods: ["GET"], auth: "optional", scopes: [] },
  { name: "health", path: "/api/v1/health", methods: ["GET"], auth: "optional", scopes: [] },
  { name: "openapi", path: "/api/v1/openapi.json", methods: ["GET"], auth: "optional", scopes: [] },
  { name: "openapi-sdk", path: "/api/v1/openapi.sdk.json", methods: ["GET"], auth: "optional", scopes: [] },
  { name: "openapi-connector", path: "/api/v1/openapi.connector.json", methods: ["GET"], auth: "optional", scopes: [] },
  { name: "search", path: "/api/v1/search", methods: ["GET"], auth: "optional", scopes: [] },
  { name: "recipes", path: "/api/v1/recipes", methods: ["GET"], auth: "optional", scopes: ["recipes:read"] },
  { name: "recipe-create", path: "/api/v1/recipes", methods: ["POST"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe", path: "/api/v1/recipes/{id}", methods: ["GET"], auth: "optional", scopes: ["recipes:read"] },
  { name: "recipe-write", path: "/api/v1/recipes/{id}", methods: ["PATCH", "DELETE"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-fork", path: "/api/v1/recipes/{id}/fork", methods: ["POST"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-import", path: "/api/v1/recipes/import", methods: ["POST"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-spoons", path: "/api/v1/recipes/{id}/spoons", methods: ["GET"], auth: "optional", scopes: ["recipes:read"] },
  { name: "recipe-spoons-create", path: "/api/v1/recipes/{id}/spoons", methods: ["POST"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-spoon", path: "/api/v1/recipes/{id}/spoons/{spoonId}", methods: ["PATCH", "DELETE"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-covers", path: "/api/v1/recipes/{id}/covers", methods: ["GET", "PATCH"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-cover", path: "/api/v1/recipes/{id}/covers/{coverId}", methods: ["PATCH", "DELETE"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-cover-regenerate", path: "/api/v1/recipes/{id}/covers/regenerate", methods: ["POST"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "recipe-cover-from-spoon", path: "/api/v1/recipes/{id}/covers/from-spoon/{spoonId}", methods: ["POST"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "cookbooks", path: "/api/v1/cookbooks", methods: ["GET"], auth: "optional", scopes: ["cookbooks:read"] },
  { name: "cookbooks-create", path: "/api/v1/cookbooks", methods: ["POST"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "cookbook", path: "/api/v1/cookbooks/{id}", methods: ["GET"], auth: "optional", scopes: ["cookbooks:read"] },
  { name: "cookbook-mutate", path: "/api/v1/cookbooks/{id}", methods: ["PATCH", "DELETE"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "cookbook-recipes", path: "/api/v1/cookbooks/{id}/recipes/{recipeId}", methods: ["POST", "DELETE"], auth: "bearer", scopes: ["kitchen:write"] },
  { name: "me", path: "/api/v1/me", methods: ["GET", "PATCH"], auth: "bearer", scopes: ["account:read", "account:write"] },
  { name: "me-photo", path: "/api/v1/me/photo", methods: ["POST", "DELETE"], auth: "bearer", scopes: ["account:write"] },
  { name: "me-notification-preferences", path: "/api/v1/me/notification-preferences", methods: ["GET", "PATCH"], auth: "bearer", scopes: ["account:read", "account:write"] },
  { name: "me-apns-devices", path: "/api/v1/me/apns-devices", methods: ["POST"], auth: "bearer", scopes: ["account:write"] },
  { name: "me-apns-device", path: "/api/v1/me/apns-devices/{deviceId}", methods: ["DELETE"], auth: "bearer", scopes: ["account:write"] },
  { name: "me-connections", path: "/api/v1/me/connections", methods: ["GET"], auth: "bearer", scopes: ["tokens:read"] },
  { name: "me-connection", path: "/api/v1/me/connections/{connectionId}", methods: ["DELETE"], auth: "bearer", scopes: ["tokens:write"] },
  { name: "shopping-list", path: "/api/v1/shopping-list", methods: ["GET"], auth: "bearer", scopes: ["shopping_list:read"] },
  { name: "shopping-list-sync", path: "/api/v1/shopping-list/sync", methods: ["GET"], auth: "bearer", scopes: ["shopping_list:read"] },
  { name: "shopping-list-items", path: "/api/v1/shopping-list/items", methods: ["POST"], auth: "bearer", scopes: ["shopping_list:write"] },
  { name: "shopping-list-item", path: "/api/v1/shopping-list/items/{itemId}", methods: ["PATCH", "DELETE"], auth: "bearer", scopes: ["shopping_list:write"] },
  { name: "shopping-list-add-from-recipe", path: "/api/v1/shopping-list/add-from-recipe", methods: ["POST"], auth: "bearer", scopes: ["shopping_list:write"] },
  { name: "shopping-list-clear-completed", path: "/api/v1/shopping-list/clear-completed", methods: ["POST"], auth: "bearer", scopes: ["shopping_list:write"] },
  { name: "shopping-list-clear-all", path: "/api/v1/shopping-list/clear-all", methods: ["POST"], auth: "bearer", scopes: ["shopping_list:write"] },
  { name: "tokens", path: "/api/v1/tokens", methods: ["GET", "POST"], auth: "bearer", scopes: ["tokens:read", "tokens:write"] },
  { name: "token", path: "/api/v1/tokens/{credentialId}", methods: ["DELETE"], auth: "bearer", scopes: ["tokens:write"] },
] as const;

export const API_V1_SCOPE_REQUIREMENTS = [
  { path: "/api/v1", method: "GET", auth: "optional", scopes: [] },
  { path: "/api/v1/health", method: "GET", auth: "optional", scopes: [] },
  { path: "/api/v1/openapi.json", method: "GET", auth: "optional", scopes: [] },
  { path: "/api/v1/openapi.sdk.json", method: "GET", auth: "optional", scopes: [] },
  { path: "/api/v1/openapi.connector.json", method: "GET", auth: "optional", scopes: [] },
  { path: "/api/v1/search", method: "GET", auth: "optional", scopes: [] },
  { path: "/api/v1/recipes", method: "GET", auth: "optional", scopes: ["recipes:read"] },
  { path: "/api/v1/recipes", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}", method: "GET", auth: "optional", scopes: ["recipes:read"] },
  { path: "/api/v1/recipes/{id}", method: "PATCH", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}", method: "DELETE", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/fork", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/import", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/spoons", method: "GET", auth: "optional", scopes: ["recipes:read"] },
  { path: "/api/v1/recipes/{id}/spoons", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/spoons/{spoonId}", method: "PATCH", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/spoons/{spoonId}", method: "DELETE", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/covers", method: "GET", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/covers", method: "PATCH", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/covers/{coverId}", method: "PATCH", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/covers/{coverId}", method: "DELETE", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/covers/regenerate", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/recipes/{id}/covers/from-spoon/{spoonId}", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/cookbooks", method: "GET", auth: "optional", scopes: ["cookbooks:read"] },
  { path: "/api/v1/cookbooks", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/cookbooks/{id}", method: "GET", auth: "optional", scopes: ["cookbooks:read"] },
  { path: "/api/v1/cookbooks/{id}", method: "PATCH", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/cookbooks/{id}", method: "DELETE", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/cookbooks/{id}/recipes/{recipeId}", method: "POST", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/cookbooks/{id}/recipes/{recipeId}", method: "DELETE", auth: "bearer", scopes: ["kitchen:write"] },
  { path: "/api/v1/me", method: "GET", auth: "bearer", scopes: ["account:read"] },
  { path: "/api/v1/me", method: "PATCH", auth: "bearer", scopes: ["account:write"] },
  { path: "/api/v1/me/photo", method: "POST", auth: "bearer", scopes: ["account:write"] },
  { path: "/api/v1/me/photo", method: "DELETE", auth: "bearer", scopes: ["account:write"] },
  { path: "/api/v1/me/notification-preferences", method: "GET", auth: "bearer", scopes: ["account:read"] },
  { path: "/api/v1/me/notification-preferences", method: "PATCH", auth: "bearer", scopes: ["account:write"] },
  { path: "/api/v1/me/apns-devices", method: "POST", auth: "bearer", scopes: ["account:write"] },
  { path: "/api/v1/me/apns-devices/{deviceId}", method: "DELETE", auth: "bearer", scopes: ["account:write"] },
  { path: "/api/v1/me/connections", method: "GET", auth: "bearer", scopes: ["tokens:read"] },
  { path: "/api/v1/me/connections/{connectionId}", method: "DELETE", auth: "bearer", scopes: ["tokens:write"] },
  { path: "/api/v1/shopping-list", method: "GET", auth: "bearer", scopes: ["shopping_list:read"] },
  { path: "/api/v1/shopping-list/sync", method: "GET", auth: "bearer", scopes: ["shopping_list:read"] },
  { path: "/api/v1/shopping-list/items", method: "POST", auth: "bearer", scopes: ["shopping_list:write"] },
  { path: "/api/v1/shopping-list/items/{itemId}", method: "PATCH", auth: "bearer", scopes: ["shopping_list:write"] },
  { path: "/api/v1/shopping-list/items/{itemId}", method: "DELETE", auth: "bearer", scopes: ["shopping_list:write"] },
  { path: "/api/v1/shopping-list/add-from-recipe", method: "POST", auth: "bearer", scopes: ["shopping_list:write"] },
  { path: "/api/v1/shopping-list/clear-completed", method: "POST", auth: "bearer", scopes: ["shopping_list:write"] },
  { path: "/api/v1/shopping-list/clear-all", method: "POST", auth: "bearer", scopes: ["shopping_list:write"] },
  { path: "/api/v1/tokens", method: "GET", auth: "bearer", scopes: ["tokens:read"] },
  { path: "/api/v1/tokens", method: "POST", auth: "bearer", scopes: ["tokens:write"] },
  { path: "/api/v1/tokens/{credentialId}", method: "DELETE", auth: "bearer", scopes: ["tokens:write"] },
] as const;

export const API_V1_ERROR_STATUS = {
  invalid_json: 400,
  validation_error: 400,
  invalid_cursor: 400,
  invalid_scope: 400,
  authentication_required: 401,
  invalid_token: 401,
  insufficient_scope: 403,
  not_found: 404,
  method_not_allowed: 405,
  idempotency_conflict: 409,
  idempotency_in_progress: 409,
  rate_limited: 429,
  upstream_error: 502,
  upstream_timeout: 504,
  internal_error: 500,
} as const;

export type ApiV1ErrorCode = keyof typeof API_V1_ERROR_STATUS;

export const API_V1_DISCOVERY_DATA = {
  app: "spoonjoy",
  version: "v1",
  status: "ok",
  docsUrl: "https://spoonjoy.app/api",
  openapiUrl: "/api/v1/openapi.json",
  sdkOpenapiUrl: "/api/v1/openapi.sdk.json",
  connectorOpenapiUrl: "/api/v1/openapi.connector.json",
  resources: API_V1_RESOURCES,
  auth: {
    modes: ["anonymous", "session", "bearer", "oauth_pkce", "delegated_agent", "mcp"],
    tokenUrl: "/api/v1/tokens",
    revokeUrl: "/api/v1/tokens/{credentialId}",
    public: {
      anonymous: true,
      note: "Public recipe and cookbook reads can be called without credentials.",
    },
    session: {
      tokenUrl: "/api/v1/tokens",
      note: "Same-origin Spoonjoy browser sessions can create personal bearer credentials.",
    },
    bearer: {
      header: "Authorization: Bearer sj_...",
      tokenUrl: "/api/v1/tokens",
      revokeUrl: "/api/v1/tokens/{credentialId}",
    },
    oauth: { register: "/oauth/register", authorize: "/oauth/authorize", token: "/oauth/token", revoke: "/oauth/revoke" },
    mcp: {
      endpoint: "/mcp",
      startAgentConnection: "/api/tools/start_agent_connection",
      pollAgentConnection: "/api/tools/poll_agent_connection",
    },
  },
} as const;
