import { describe, it, expect, vi } from "vitest";
import {
  IMAGE_FALLBACK_ERROR_CODES,
  ImageGenError,
  composePlaceholderPrompt,
  composeStylizationFallbackPrompt,
  composeStylizationPrompt,
  createOpenAIImageRunner,
  generatePlaceholderImage,
  makeFallbackPlaceholderSvg,
  stylizeSpoonPhoto,
  type ImageGenDeps,
  type ImageGenRunner,
} from "~/lib/image-gen.server";

const GENERATED_BYTES = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 1, 2, 3]);
const VALID_PNG_BYTES = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 1, 2, 3]);
const VALID_JPEG_BYTES = new Uint8Array([0xff, 0xd8, 0xff, 0xe0, 1, 2, 3]);
const GIF_BYTES = new Uint8Array([0x47, 0x49, 0x46, 0x38, 0x39, 0x61]);

function b64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

function dataUrl(contentType: string, bytes: Uint8Array): string {
  return `data:${contentType};base64,${b64(bytes)}`;
}

function mockR2(): R2Bucket {
  return {
    put: vi.fn(async () => ({})),
    delete: vi.fn(async () => undefined),
    get: vi.fn(),
    head: vi.fn(),
    list: vi.fn(),
    createMultipartUpload: vi.fn(),
    resumeMultipartUpload: vi.fn(),
  } as unknown as R2Bucket;
}

function mockFetchReturning(bytes: Uint8Array): typeof fetch {
  return vi.fn(async () => ({
    ok: true,
    arrayBuffer: async () => bytes.buffer as ArrayBuffer,
  })) as unknown as typeof fetch;
}

function mockRunner(overrides: Partial<ImageGenRunner> = {}): ImageGenRunner {
  return {
    textToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES, contentType: "image/png" })),
    imageToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES, contentType: "image/png" })),
    ...overrides,
  };
}

describe("image-gen.server prompts and constants", () => {
  it("composes the placeholder prompt verbatim with title + description", () => {
    const prompt = composePlaceholderPrompt("Tomato Soup", "warming and rich");
    expect(prompt).toContain("Warm editorial food photograph of Tomato Soup, warming and rich.");
    expect(prompt).toContain("Plated on cream ceramic with brass-toned cutlery");
    expect(prompt).toContain("No text, no watermarks, no people.");
  });

  it("omits the description clause when description is null", () => {
    const prompt = composePlaceholderPrompt("Tomato Soup", null);
    expect(prompt).toContain("Warm editorial food photograph of Tomato Soup.");
    expect(prompt).not.toContain(", null");
    expect(prompt).not.toContain("Tomato Soup, .");
  });

  it("returns the verbatim stylization prompt", () => {
    expect(composeStylizationPrompt()).toContain(
      "Restyle this photograph as warm editorial cookbook photography",
    );
  });

  it("returns a text-only fallback prompt for DALL-E 3", () => {
    const prompt = composeStylizationFallbackPrompt("Tomato Soup");
    expect(prompt).toContain("Restyle this photograph");
    expect(prompt).toContain("warm editorial cookbook photography");
    expect(prompt).toContain("Tomato Soup");
  });

  it("re-exports the SVG fallback helper", () => {
    const { url } = makeFallbackPlaceholderSvg("X");
    expect(url.startsWith("data:image/svg+xml;base64,")).toBe(true);
  });

  it("declares the OpenAI fallback error codes", () => {
    expect(IMAGE_FALLBACK_ERROR_CODES).toEqual([
      "model_not_found",
      "model_unsupported",
      "404",
    ]);
  });
});

describe("generatePlaceholderImage", () => {
  it("calls textToImage with the composed prompt and the DALL-E 3 model", async () => {
    const runner = mockRunner();
    const deps: ImageGenDeps = {
      env: {},
      runner,
      bucket: mockR2(),
      now: () => 12345,
      randomId: () => "generated-id",
    };
    await generatePlaceholderImage("Pasta", "fresh and bright", deps);
    expect(runner.textToImage).toHaveBeenCalledWith(
      composePlaceholderPrompt("Pasta", "fresh and bright"),
      { model: "dall-e-3" },
    );
  });

  it("uploads generated bytes to R2 under a unique covers key and returns /photos/...", async () => {
    const bucket = mockR2();
    const fetchImpl = vi.fn() as unknown as typeof fetch;
    const deps: ImageGenDeps = {
      env: {},
      runner: mockRunner(),
      fetchImpl,
      bucket,
      now: () => 4242,
      randomId: () => "uuid-a",
    };
    const url = await generatePlaceholderImage("Cake", null, deps);
    expect(url).toBe("/photos/covers/4242-uuid-a.png");
    expect(bucket.put).toHaveBeenCalledWith(
      "covers/4242-uuid-a.png",
      GENERATED_BYTES,
      expect.objectContaining({ httpMetadata: { contentType: "image/png" } }),
    );
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  it("uses unique generated cover keys for same-millisecond calls", async () => {
    const bucket = mockR2();
    const ids = ["uuid-a", "uuid-b"];
    await generatePlaceholderImage("Cake", null, {
      env: {},
      runner: mockRunner(),
      bucket,
      now: () => 4242,
      randomId: () => ids.shift()!,
    });
    await generatePlaceholderImage("Cake", null, {
      env: {},
      runner: mockRunner(),
      bucket,
      now: () => 4242,
      randomId: () => ids.shift()!,
    });
    expect((bucket.put as ReturnType<typeof vi.fn>).mock.calls.map(([key]) => key))
      .toEqual(["covers/4242-uuid-a.png", "covers/4242-uuid-b.png"]);
  });

  it("uses file extensions matching non-PNG generated content types", async () => {
    const bucket = mockR2();
    await generatePlaceholderImage("Cake", null, {
      env: {},
      runner: mockRunner({
        textToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES, contentType: "image/jpeg" })),
      }),
      bucket,
      now: () => 1,
      randomId: () => "jpeg-id",
    });
    await generatePlaceholderImage("Cake", null, {
      env: {},
      runner: mockRunner({
        textToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES, contentType: "image/webp" })),
      }),
      bucket,
      now: () => 2,
      randomId: () => "webp-id",
    });
    expect((bucket.put as ReturnType<typeof vi.fn>).mock.calls.map(([key]) => key))
      .toEqual(["covers/1-jpeg-id.jpg", "covers/2-webp-id.webp"]);
  });

  it("defaults generated byte content type to PNG", async () => {
    const bucket = mockR2();
    await generatePlaceholderImage("Cake", null, {
      env: {},
      runner: mockRunner({
        textToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES })),
      }),
      bucket,
      now: () => 3,
      randomId: () => "default-type",
    });
    expect(bucket.put).toHaveBeenCalledWith(
      "covers/3-default-type.png",
      GENERATED_BYTES,
      expect.objectContaining({ httpMetadata: { contentType: "image/png" } }),
    );
  });

  it("returns a deterministic data URL when bucket is absent and local fallback is explicit", async () => {
    const url = await generatePlaceholderImage("Cake", null, {
      env: {},
      runner: mockRunner(),
      allowLocalImageFallback: true,
    });
    expect(url).toBe(`data:image/png;base64,${b64(GENERATED_BYTES)}`);
  });

  it("throws when bucket is absent and local fallback is not explicit", async () => {
    await expect(
      generatePlaceholderImage("Cake", null, {
        env: {},
        runner: mockRunner(),
      }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });

  it("throws when generated output has empty bytes and no URL", async () => {
    await expect(
      generatePlaceholderImage("Cake", null, {
        env: {},
        runner: mockRunner({
          textToImage: vi.fn(async () => ({ bytes: new Uint8Array(), contentType: "image/png" })),
        }),
        bucket: mockR2(),
      }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });

  it("wraps runner failures in ImageGenError preserving the cause", async () => {
    const cause = new Error("boom");
    const runner = mockRunner({
      textToImage: vi.fn(async () => {
        throw cause;
      }),
    });
    await expect(
      generatePlaceholderImage("X", null, { env: {}, runner }),
    ).rejects.toMatchObject({ name: "ImageGenError", cause });
  });

  it("throws ImageGenError when the bucket fetch returns a non-OK response", async () => {
    const failingFetch = vi.fn(async () => ({
      ok: false,
      status: 503,
      arrayBuffer: async () => new ArrayBuffer(0),
    })) as unknown as typeof fetch;
    await expect(
      generatePlaceholderImage("X", null, {
        env: {},
        runner: mockRunner({
          textToImage: vi.fn(async () => ({ url: "https://openai.test/x.png" })),
        }),
        fetchImpl: failingFetch,
        bucket: mockR2(),
        now: () => 1,
      }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });

  it("falls back to global fetch for legacy URL outputs", async () => {
    const originalFetch = globalThis.fetch;
    const fetchSpy = vi.fn(async () => ({
      ok: true,
      arrayBuffer: async () => GENERATED_BYTES.buffer as ArrayBuffer,
    }));
    globalThis.fetch = fetchSpy as unknown as typeof fetch;
    try {
      const bucket = mockR2();
      const url = await generatePlaceholderImage("Cake", null, {
        env: {},
        runner: mockRunner({
          textToImage: vi.fn(async () => ({ url: "https://openai.test/legacy.png" })),
        }),
        bucket,
        now: () => 4,
        randomId: () => "legacy-url",
      });
      expect(url).toBe("/photos/covers/4-legacy-url.png");
      expect(fetchSpy).toHaveBeenCalledWith("https://openai.test/legacy.png");
    } finally {
      globalThis.fetch = originalFetch;
    }
  });
});

describe("stylizeSpoonPhoto", () => {
  it("resolves a data URL source to a validated File before imageToImage", async () => {
    const runner = mockRunner({
      imageToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES, contentType: "image/png" })),
    });
    const rawPhotoUrl = dataUrl("image/png", VALID_PNG_BYTES);
    const deps: ImageGenDeps = {
      env: {},
      runner,
      bucket: mockR2(),
      now: () => 1,
      randomId: () => "img-id",
    };
    await stylizeSpoonPhoto(rawPhotoUrl, "Tomato Soup", deps);
    expect(runner.imageToImage).toHaveBeenCalledWith(
      expect.any(File),
      composeStylizationPrompt(),
      { model: "gpt-image-1" },
    );
    const sourceFile = (runner.imageToImage as ReturnType<typeof vi.fn>).mock.calls[0][0] as File;
    expect(sourceFile.type).toBe("image/png");
    expect(new Uint8Array(await sourceFile.arrayBuffer())).toEqual(VALID_PNG_BYTES);
  });

  it("resolves an R2 /photos source to a validated File before imageToImage", async () => {
    const runner = mockRunner();
    const bucket = mockR2();
    bucket.get = vi.fn(async () => ({
      arrayBuffer: async () => VALID_PNG_BYTES.buffer,
      httpMetadata: { contentType: "image/png" },
    })) as unknown as R2Bucket["get"];

    await stylizeSpoonPhoto("/photos/recipes/u/r/raw.png", "Tomato Soup", {
      env: {},
      runner,
      bucket,
      now: () => 2,
      randomId: () => "r2-id",
    });

    expect(bucket.get).toHaveBeenCalledWith("recipes/u/r/raw.png");
    const sourceFile = (runner.imageToImage as ReturnType<typeof vi.fn>).mock.calls[0][0] as File;
    expect(sourceFile.name).toBe("raw.png");
    expect(sourceFile.type).toBe("image/png");
  });

  it("fetches an HTTPS source through the safe image fetch path before imageToImage", async () => {
    const runner = mockRunner();
    const fetchImpl = vi.fn(async () => new Response(VALID_JPEG_BYTES, {
      headers: { "content-type": "image/jpeg" },
    })) as unknown as typeof fetch;

    await stylizeSpoonPhoto("https://photos.example/raw.jpg", "Tomato Soup", {
      env: {},
      runner,
      bucket: mockR2(),
      fetchImpl,
      now: () => 3,
      randomId: () => "https-id",
    });

    expect(fetchImpl).toHaveBeenCalledWith(
      "https://photos.example/raw.jpg",
      expect.objectContaining({ redirect: "manual", signal: expect.any(AbortSignal) }),
    );
    const sourceFile = (runner.imageToImage as ReturnType<typeof vi.fn>).mock.calls[0][0] as File;
    expect(sourceFile.type).toBe("image/jpeg");
  });

  it("rejects plaintext HTTP source URLs before imageToImage", async () => {
    const runner = mockRunner();
    const fetchImpl = vi.fn(async () => new Response(VALID_JPEG_BYTES, {
      headers: { "content-type": "image/jpeg" },
    })) as unknown as typeof fetch;

    await expect(
      stylizeSpoonPhoto("http://photos.example/raw.jpg", "Tomato Soup", {
        env: {},
        runner,
        bucket: mockR2(),
        fetchImpl,
      }),
    ).rejects.toBeInstanceOf(ImageGenError);

    expect(fetchImpl).not.toHaveBeenCalled();
    expect(runner.imageToImage).not.toHaveBeenCalled();
  });

  it("uses a fallback filename for HTTPS source URLs without a path filename", async () => {
    const runner = mockRunner();
    const fetchImpl = vi.fn(async () => new Response(VALID_JPEG_BYTES, {
      headers: { "content-type": "image/jpeg" },
    })) as unknown as typeof fetch;

    await stylizeSpoonPhoto("https://photos.example/", "Tomato Soup", {
      env: {},
      runner,
      bucket: mockR2(),
      fetchImpl,
      now: () => 30,
      randomId: () => "fallback-name",
    });

    const sourceFile = (runner.imageToImage as ReturnType<typeof vi.fn>).mock.calls[0][0] as File;
    expect(sourceFile.name).toBe("source.jpg");
  });

  it("does not fall back to text generation after an image edit failure", async () => {
    const fallbackErr = Object.assign(new Error("nope"), { code: "model_not_found" });
    const runner = mockRunner({
      imageToImage: vi.fn(async () => {
        throw fallbackErr;
      }),
      textToImage: vi.fn(async () => ({ url: "https://openai.test/fallback.png" })),
    });
    await expect(
      stylizeSpoonPhoto(dataUrl("image/png", VALID_PNG_BYTES), "Pasta", {
        env: {},
        runner,
        bucket: mockR2(),
      }),
    ).rejects.toBeInstanceOf(ImageGenError);
    expect(runner.textToImage).not.toHaveBeenCalled();
  });

  it("returns usedModel=gpt-image-1 when the primary call succeeds", async () => {
    const runner = mockRunner({
      imageToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES, contentType: "image/png" })),
    });
    const result = await stylizeSpoonPhoto(dataUrl("image/png", VALID_PNG_BYTES), "X", {
      env: {},
      runner,
      bucket: mockR2(),
      now: () => 8,
      randomId: () => "primary-id",
    });
    expect(result.usedModel).toBe("gpt-image-1");
  });

  it("rethrows as ImageGenError on a non-fallback error", async () => {
    const runner = mockRunner({
      imageToImage: vi.fn(async () => {
        const err = Object.assign(new Error("rate"), { code: "rate_limit" });
        throw err;
      }),
    });
    await expect(
      stylizeSpoonPhoto(dataUrl("image/png", VALID_PNG_BYTES), "X", { env: {}, runner }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });

  it("rejects unsafe source bytes before imageToImage", async () => {
    const runner = mockRunner({
      textToImage: vi.fn(async () => ({ bytes: GENERATED_BYTES, contentType: "image/png" })),
    });
    await expect(
      stylizeSpoonPhoto(dataUrl("image/gif", GIF_BYTES), "X", { env: {}, runner, bucket: mockR2() }),
    ).rejects.toBeInstanceOf(ImageGenError);
    expect(runner.imageToImage).not.toHaveBeenCalled();
    expect(runner.textToImage).not.toHaveBeenCalled();
  });

  it("rejects stored /photos sources when no bucket is available", async () => {
    const runner = mockRunner();
    await expect(
      stylizeSpoonPhoto("/photos/recipes/u/r/raw.png", "X", { env: {}, runner }),
    ).rejects.toBeInstanceOf(ImageGenError);
    expect(runner.imageToImage).not.toHaveBeenCalled();
  });

  it("rejects stored /photos sources when the object is missing", async () => {
    const runner = mockRunner();
    const bucket = mockR2();
    bucket.get = vi.fn(async () => null) as unknown as R2Bucket["get"];
    await expect(
      stylizeSpoonPhoto("/photos/recipes/u/r/raw.png", "X", { env: {}, runner, bucket }),
    ).rejects.toBeInstanceOf(ImageGenError);
    expect(runner.imageToImage).not.toHaveBeenCalled();
  });

  it("rejects stored /photos sources when content type metadata is missing", async () => {
    const runner = mockRunner();
    const bucket = mockR2();
    bucket.get = vi.fn(async () => ({
      arrayBuffer: async () => VALID_PNG_BYTES.buffer,
      httpMetadata: {},
    })) as unknown as R2Bucket["get"];
    await expect(
      stylizeSpoonPhoto("/photos/recipes/u/r/raw.png", "X", { env: {}, runner, bucket }),
    ).rejects.toBeInstanceOf(ImageGenError);
    expect(runner.imageToImage).not.toHaveBeenCalled();
  });

  it("rejects malformed source URLs before imageToImage", async () => {
    const runner = mockRunner();
    await expect(
      stylizeSpoonPhoto("not a url", "X", { env: {}, runner, bucket: mockR2() }),
    ).rejects.toBeInstanceOf(ImageGenError);
    expect(runner.imageToImage).not.toHaveBeenCalled();
  });

  it("rejects unsupported source URL schemes before imageToImage", async () => {
    const runner = mockRunner();
    await expect(
      stylizeSpoonPhoto("file:///tmp/raw.png", "X", { env: {}, runner, bucket: mockR2() }),
    ).rejects.toBeInstanceOf(ImageGenError);
    expect(runner.imageToImage).not.toHaveBeenCalled();
  });

  it("returns a data URL when bucket is absent on success and local fallback is explicit", async () => {
    const runner = mockRunner();
    const result = await stylizeSpoonPhoto(dataUrl("image/png", VALID_PNG_BYTES), "X", {
      env: {},
      runner,
      allowLocalImageFallback: true,
    });
    expect(result.url).toBe(`data:image/png;base64,${b64(GENERATED_BYTES)}`);
  });

  it("throws when stylization succeeds without a bucket or explicit local fallback", async () => {
    await expect(
      stylizeSpoonPhoto(dataUrl("image/png", VALID_PNG_BYTES), "X", {
        env: {},
        runner: mockRunner(),
      }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });
});

describe("createOpenAIImageRunner", () => {
  it("calls client.images.generate for textToImage and decodes b64_json", async () => {
    const generate = vi.fn(async () => ({ data: [{ b64_json: b64(GENERATED_BYTES) }] }));
    const runner = createOpenAIImageRunner({
      images: { generate, edit: vi.fn() },
    });
    const result = await runner.textToImage("prompt", { model: "dall-e-3" });
    expect(generate).toHaveBeenCalledWith({
      prompt: "prompt",
      model: "dall-e-3",
      n: 1,
      size: "1024x1024",
      response_format: "b64_json",
    });
    expect(result).toEqual({ bytes: GENERATED_BYTES, contentType: "image/png" });
  });

  it("calls client.images.edit for imageToImage and decodes b64_json", async () => {
    const edit = vi.fn(async () => ({ data: [{ b64_json: b64(GENERATED_BYTES) }] }));
    const runner = createOpenAIImageRunner({
      images: { generate: vi.fn(), edit },
    });
    const sourceFile = new File([VALID_PNG_BYTES], "raw.png", { type: "image/png" });
    const result = await runner.imageToImage(
      sourceFile,
      "prompt",
      { model: "gpt-image-1" },
    );
    expect(edit).toHaveBeenCalledWith(
      expect.objectContaining({
        image: sourceFile,
        prompt: "prompt",
        model: "gpt-image-1",
      }),
    );
    expect(result).toEqual({ bytes: GENERATED_BYTES, contentType: "image/png" });
  });

  it("throws when the OpenAI response contains neither b64_json nor URL", async () => {
    const runner = createOpenAIImageRunner({
      images: {
        generate: vi.fn(async () => ({ data: [{}] })),
        edit: vi.fn(),
      },
    });
    await expect(runner.textToImage("p", { model: "dall-e-3" })).rejects.toBeInstanceOf(
      ImageGenError,
    );
  });

  it("still returns URL responses for legacy image clients", async () => {
    const runner = createOpenAIImageRunner({
      images: {
        generate: vi.fn(async () => ({ data: [{ url: "https://openai.test/legacy.png" }] })),
        edit: vi.fn(),
      },
    });
    await expect(runner.textToImage("p", { model: "dall-e-3" }))
      .resolves.toEqual({ url: "https://openai.test/legacy.png" });
  });

  it("treats non-object thrown values as non-fallback errors", async () => {
    const runner = mockRunner({
      imageToImage: vi.fn(async () => {
        // Throw a string (not an object) — must not enter the fallback branch.
        // eslint-disable-next-line @typescript-eslint/no-throw-literal
        throw "boom";
      }),
    });
    await expect(
      stylizeSpoonPhoto(dataUrl("image/png", VALID_PNG_BYTES), "X", { env: {}, runner }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });

  it("treats non-string error codes as non-fallback errors", async () => {
    const runner = mockRunner({
      imageToImage: vi.fn(async () => {
        throw Object.assign(new Error("weird"), { code: 404 });
      }),
    });
    await expect(
      stylizeSpoonPhoto(dataUrl("image/png", VALID_PNG_BYTES), "X", { env: {}, runner }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });

  it("falls back to Date.now and crypto.randomUUID when no overrides are supplied", async () => {
    const originalNow = Date.now;
    const originalRandomUUID = crypto.randomUUID;
    const stamp = 999_000;
    Date.now = () => stamp;
    crypto.randomUUID = vi.fn(() => "crypto-id") as unknown as Crypto["randomUUID"];
    try {
      const bucket = mockR2();
      const url = await generatePlaceholderImage("X", null, {
        env: {},
        runner: mockRunner(),
        bucket,
      });
      expect(url).toBe(`/photos/covers/${stamp}-crypto-id.png`);
    } finally {
      Date.now = originalNow;
      crypto.randomUUID = originalRandomUUID;
    }
  });

  it("throws when imageToImage returns no URL", async () => {
    const runner = createOpenAIImageRunner({
      images: {
        generate: vi.fn(),
        edit: vi.fn(async () => ({ data: [{}] })),
      },
    });
    await expect(
      runner.imageToImage(new File([VALID_PNG_BYTES], "raw.png", { type: "image/png" }), "p", { model: "gpt-image-1" }),
    ).rejects.toBeInstanceOf(ImageGenError);
  });
});
