import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("logout", "routes/logout.tsx"),
  route("auth/google", "routes/auth.google.tsx"),
  route("auth/google/callback", "routes/auth.google.callback.tsx"),
  route("auth/github", "routes/auth.github.tsx"),
  route("auth/github/callback", "routes/auth.github.callback.tsx"),
  route("auth/apple", "routes/auth.apple.tsx"),
  route("auth/apple/callback", "routes/auth.apple.callback.tsx"),
  route(".redwood/functions/auth/oauth", "routes/redwood-functions-auth-oauth.tsx"),
  route("search", "routes/search.tsx"),
  route("og/recipes/:id.png", "routes/og.recipes.$id.png.tsx"),
  route("og/cookbooks/:id.png", "routes/og.cookbooks.$id.png.tsx"),
  route("recipes", "routes/recipes.tsx", [
    index("routes/recipes._index.tsx"),
    route("new", "routes/recipes.new.tsx"),
    route(":id", "routes/recipes.$id.tsx"),
    route(":id/edit", "routes/recipes.$id.edit.tsx"),
    route(":id/fork", "routes/recipes.$id.fork.tsx"),
    route(":id/steps/new", "routes/recipes.$id.steps.new.tsx"),
    route(":id/steps/:stepId/edit", "routes/recipes.$id.steps.$stepId.edit.tsx"),
  ]),
  route("cookbooks", "routes/cookbooks.tsx", [
    index("routes/cookbooks._index.tsx"),
    route("new", "routes/cookbooks.new.tsx"),
    route(":id", "routes/cookbooks.$id.tsx"),
  ]),
  route("shopping-list", "routes/shopping-list.tsx"),
  route("account/settings", "routes/account.settings.tsx"),
  route("users/:identifier", "routes/users.$identifier.tsx"),
  route("users/:identifier/fellow-chefs", "routes/users.$identifier.fellow-chefs.tsx"),
  route("users/:identifier/kitchen-visitors", "routes/users.$identifier.kitchen-visitors.tsx"),
  route("api/push/public-key", "routes/api.push.public-key.ts"),
  route("api/push/subscriptions", "routes/api.push.subscriptions.ts"),
  route("api/push/preferences", "routes/api.push.preferences.ts"),
  route("api/*", "routes/api.$.ts"),
  route("photos/*", "routes/photos.$.tsx"),
  route(".well-known/appspecific/com.chrome.devtools.json", "routes/devtools-well-known.tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
